apiVersion: v1
kind: Pod
metadata:
  name: yingwu
  namespace: hyperfaas
spec:
  containers:
  - name: yingwu
    image: zhangjyr/yingwu:b1
    imagePullPolicy: Always
    # resources:
    #   requests:
    #     cpu: "300m"
    #   limits:
    #     cpu: "300m"
    # trivial
    # command: [ "/yingwu", "-d", "60", "-c", "30", "-h", "3", "-o", "hello.txt", "-p", "multiphase" ]
    # cpu
    command: [ "/yingwu", "-d", "60", "-c", "20", "-h", "2", "-o", "cpu.txt", "-p", "scaleout", "-f", "benchmark_cpu" ]
