apiVersion: v1
kind: Pod
metadata:
  name: yingwu
  namespace: hyperfaas
spec:
  containers:
  - name: yingwu
    image: zhangjyr/yingwu:b1
    imagePullPolicy: Always
    # resources:
    #   requests:
    #     cpu: "300m"
    #   limits:
    #     cpu: "300m"
    command: [ "/yingwu", "-d", "60", "-c", "50", "-h", "10", "-data", "data.txt" ]
