apiVersion: v1
kind: Pod
metadata:
  name: fe-%s
  namespace: hyperfaas
spec:
  containers:
  - name: ics
    image: zhangjyr/go2env:b1
    resources:
      requests:
        cpu: "500m"
      limits:
        cpu: "1"
    env:
    - name: profile
      value: "/profile.log"
    - name: faas
      value: "%s"
