# apiVersion: v1
# kind: ServiceAccount
# metadata:
#   name: hyperfaas
#   namespace: kube-system
# ---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  labels:
    kubernetes.io/bootstrapping: rbac-defaults
  name: system:hyperfaas
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - watch
  - create
  - delete
  - update
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  annotations:
    rbac.authorization.kubernetes.io/autoupdate: "true"
  labels:
    kubernetes.io/bootstrapping: rbac-defaults
  name: system:hyperfaas
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:hyperfaas
subjects:
- kind: ServiceAccount
  # name: hyperfaas
  # namespace: kube-system
  name: default
  namespace: hyperfaas
